let month30=[]

export const dataElement3=[
    {
        name:'Март',
        day:'1',
        week:'ПТ'
    },
    {
        name:'Март',
        day:'2',
        week:'СБ'
    },
    {
        name:'Март',
        day:'3',
        week:'ВС'
    },
    {
        name:'Март',
        day:'4',
        week:'ПН'
    },
    {
        name:'Март',
        day:'5',
        week:'ВТ'
    },
    {
        name:'Март',
        day:'6',
        week:'СР'
    },
    {
        name:'Март',
        day:'7',
        week:'ЧТ'
    },
    {
        name:'Март',
        day:'8',
        week:'ПТ'
    },
    {
        name:'Март',
        day:'9',
        week:'СБ'
    },
    {
        name:'Март',
        day:'10',
        week:'ВС'
    },
    {
        name:'Март',
        day:'11',
        week:'ПН'
    },
    {
        name:'Март',
        day:'12',
        week:'ВТ'
    },
    {
        name:'Март',
        day:'13',
        week:'СР'
    },
    {
        name:'Март',
        day:'14',
        week:'ЧТ'
    },
    {
        name:'Март',
        day:'15',
        week:'ПТ'
    },
    {
        name:'Март',
        day:'16',
        week:'СБ'
    },
    {
        name:'Март',
        day:'17',
        week:'ВС'
    },
    {
        name:'Март',
        day:'18',
        week:'ПН'
    },
    {
        name:'Март',
        day:'19',
        week:'ВТ'
    },
    {
        name:'Март',
        day:'20',
        week:'СР'
    },
    {
        name:'Март',
        day:'21',
        week:'ЧТ'
    },
    {
        name:'Март',
        day:'22',
        week:'ПТ'
    },
    {
        name:'Март',
        day:'23',
        week:'СБ'
    },
    {
        name:'Март',
        day:'24',
        week:'ВС'
    },
    {
        name:'Март',
        day:'25',
        week:'ПН'
    },
    {
        name:'Март',
        day:'26',
        week:'ВТ'
    },
    {
        name:'Март',
        day:'27',
        week:'СР'
    },
    {
        name:'Март',
        day:'28',
        week:'ЧТ'
    },
    {
        name:'Март',
        day:'29',
        week:'ПТ'
    },
    {
        name:'Март',
        day:'30',
        week:'СБ'
    },
    {
        name:'Март',
        day:'31',
        week:'ВС'
    },
    {
        name:'Апрель',
        day:'1',
        week:'ПН'
    },
    {
        name:'Апрель',
        day:'2',
        week:'ВТ'
    },
    {
        name:'Апрель',
        day:'3',
        week:'СР'
    },
    {
        name:'Апрель',
        day:'4',
        week:'ЧТ'
    },
    {
        name:'Апрель',
        day:'5',
        week:'ПТ'
    },
    {
        name:'Апрель',
        day:'6',
        week:'СБ'
    },
    {
        name:'Апрель',
        day:'7',
        week:'ВС'
    },
    {
        name:'Апрель',
        day:'8',
        week:'ПН'
    },
    {
        name:'Апрель',
        day:'9',
        week:'ВТ'
    },
    {
        name:'Апрель',
        day:'10',
        week:'СР'
    },
    {
        name:'Апрель',
        day:'11',
        week:'ЧТ'
    },
    {
        name:'Апрель',
        day:'12',
        week:'ПТ'
    },
    {
        name:'Апрель',
        day:'13',
        week:'СБ'
    },
    {
        name:'Апрель',
        day:'14',
        week:'ВС'
    },
    {
        name:'Апрель',
        day:'15',
        week:'ПН'
    },
    {
        name:'Апрель',
        day:'16',
        week:'ВТ'
    },
    {
        name:'Апрель',
        day:'17',
        week:'СР'
    },
    {
        name:'Апрель',
        day:'18',
        week:'ЧТ'
    },
    {
        name:'Апрель',
        day:'19',
        week:'ПТ'
    },
    {
        name:'Апрель',
        day:'20',
        week:'СБ'
    },
    {
        name:'Апрель',
        day:'21',
        week:'ВС'
    },
    {
        name:'Апрель',
        day:'22',
        week:'ПН'
    },
    {
        name:'Апрель',
        day:'23',
        week:'ВТ'
    },
    {
        name:'Апрель',
        day:'24',
        week:'СР'
    },
    {
        name:'Апрель',
        day:'25',
        week:'ЧТ'
    },
    {
        name:'Апрель',
        day:'26',
        week:'ПТ'
    },
    {
        name:'Апрель',
        day:'27',
        week:'СБ'
    },
    {
        name:'Апрель',
        day:'28',
        week:'ВС'
    },
    {
        name:'Апрель',
        day:'29',
        week:'ПН'
    },
    {
        name:'Апрель',
        day:'30',
        week:'ВТ'
    }
    
]

export const dataElement3Month=[
    {
        name:'Март'
    },
    {
        name:'Апрель'
    }
]